.ig
	@(#)getpid.2	1.2	6/30/83
	@(#)Copyright (C) 1983 by National Semiconductor Corp.
..
.TH GETPID 2 
.SH NAME
getpid \- get process identification
.SH SYNOPSIS
.B getpid()
.SH DESCRIPTION
.I Getpid
returns
the process ID of
the current process.
Most often it is used to generate
uniquely-named
temporary files.
.SH "SEE ALSO"
mktemp(3)
