.ig
	@(#)setuid.2	1.2	6/30/83
	@(#)Copyright (C) 1983 by National Semiconductor Corp.
..
.TH SETUID 2 
.SH NAME
setuid, setgid \- set user and group ID
.SH SYNOPSIS
.B setuid(uid)
.PP
.B setgid(gid)
.SH DESCRIPTION
The user ID (group ID) of the current process is set to
the argument.
Both the effective and the real ID are set.
These calls are only permitted to the super-user
or if the argument is the real or effective ID.
.SH "SEE ALSO"
getuid(2)
.SH DIAGNOSTICS
Zero is returned if the user (group) ID is set;
\-1 is returned otherwise.
