.ig
	@(#)ar.5	1.5	9/20/83
	@(#)Copyright (C) 1983 by National Semiconductor Corp.
..
.TH AR 5
.SH NAME
ar \- archive (library) file format
.SH SYNOPSIS
.B # include <ar.h>
.SH DESCRIPTION
The archive command
.I ar
is used to combine several files into
one.
Archives are used mainly as libraries to be searched
by the link-editor
.I ld.
.PP
A file produced by
.I ar
has a magic string at the start,
followed by the constituent files, each preceded by a file header.
The magic number and header layout as described in the
include file are:
.RS
.PP
.nf
.ta \w'# define 'u +\w'SARMAG 'u
.ec %
.\".so /v/mesaux/include/ar.h
/*
 * ar.h:
 */

# define	ARMAG	"!<arch>\n"
# define	SARMAG	8

# define	ARFMAG	"`\n"

struct ar_hdr {
	char	ar_name[16];
	char	ar_date[12];
	char	ar_uid[6];
	char	ar_gid[6];
	char	ar_mode[8];
	char	ar_size[10];
	char	ar_fmag[2];
};
.ec \
.fi
.RE
.LP
The name is a blank-padded string.
The
.I ar_fmag
field contains ARFMAG
to help verify the presence of a header.
The other fields are left-adjusted, blank-padded numbers.
They are decimal except for
.IR ar_mode ,
which is octal.
The date is the modification date of the file
at the time of its insertion into the archive.
.PP
Each file begins on an even (0 mod 2) boundary;
a new-line is inserted between files if necessary.
Nevertheless, the size given reflects the
actual size of the file exclusive of padding.
.PP
There is no provision for empty areas in an archive
file.
.PP
The encoding of the header is portable across machines.
If an archive contains printable files, the archive itself
is printable.
.SH "SEE ALSO"
ar(1), ld(1), nm(1)
.SH BUGS
File names lose trailing blanks.
Most software dealing with archives takes even
an included blank as a name terminator.
