.ig
	@(#)intro.4	1.5	10/20/83
	@(#)Copyright (C) 1983 by National Semiconductor Corp.
..
.TH INTRO 4
.SH NAME
intro \- introduction to special files
.SH DESCRIPTION
This section describes the special files and related driver functions
available on the system.
The DIAGNOSTICS section lists messages
that may appear on the console
and in the system error log
.I /usr/adm/messages
due to errors in device operation.
