.ig
	@(#)cb.1	1.2	6/29/83
	@(#)Copyright (C) 1983 by National Semiconductor Corp.
..
.TH CB 1
.SH NAME
cb \- C program beautifier
.SH SYNOPSIS
.B cb
.SH DESCRIPTION
.I Cb
places a copy of the C program from the standard input
on the standard output with spacing and indentation
that displays the structure of the program.
.SH BUGS
