.ig
	@(#)help.1	1.2	6/29/83
	@(#)Copyright (C) 1983 by National Semiconductor Corp.
..
.TH HELP 1
.SH NAME
help \- give pointers to system documentation
.SH SYNOPSIS
.B
help
.SH DESCRIPTION
.I Help
prints a fixed message that tells novice users where to look for basic
information about the system.
.SH SEE ALSO
apropos(1), man(1), sccshelp(1)
