.ig
	@(#)rev.1	1.2	6/29/83
	@(#)Copyright (C) 1983 by National Semiconductor Corp.
..
.TH REV 1
.SH NAME
rev \- reverse lines of a file
.SH SYNOPSIS
.B rev
[ file ] ...
.SH DESCRIPTION
.I Rev
copies the named files to the standard output,
reversing the order of characters in every line.
If no file is specified, the standard input is copied.
