.ig
	@(#)sccsdiff.1	1.4	6/29/83
	@(#)Copyright (C) 1983 by National Semiconductor Corp.
..
.TH SCCSDIFF 1
.SH NAME
sccsdiff \- compare two versions of an \s-1SCCS\s0 file
.SH SYNOPSIS
.B sccsdiff
.BR \-r \s-1SID\s0\&1
.BR \-r \s-1SID\s0\&2
.RB [ \-p ]
.RB [ \-s n]
files
.SH DESCRIPTION
.I Sccsdiff\^
compares two versions of an
.SM SCCS
file and generates the differences between the
two versions.
Any number of
.SM SCCS
files may be specified, but arguments apply to all files.
.RS 5
.TP 12
.BI \-r \s-1SID\s0?\^
.IR \s-1SID\s0\&1 \ and \ \s-1SID\s0\&2 \ specify
the deltas of an
.SM SCCS
file that are to be compared.
Versions are passed to
.IR bdiff (1)
in the order given.
.TP 12
.B \-p
pipe output for each file through
.IR pr (1).
.TP 12
.BI \-s n\^
\fIn\fP is the file segment size that
.I bdiff\^
will pass to
.IR diff (1).
This is useful when
.I diff\^
fails due to a high system load.
.SH FILES
.TP "\w'/tmp/get?????\ \ 'u"
/tmp/get?????
Temporary files
.SH "SEE ALSO"
bdiff(1),
get(1),
sccs(1),
sccshelp(1),
pr(1).
.br
.IR "Source Code Control System User's Guide" by
L. E. Bonanni and C. A. Salemi.
.SH DIAGNOSTICS
.PD 0
.TP 25
.RI `` file ": No differences''"
If the two versions are the same.
.PP
Use
.IR sccshelp (1)
for explanations.
.PD
