.ig
	@(#)stat.1	1.2	6/29/83
	@(#)Copyright (C) 1983 by National Semiconductor Corp.
..
.TH STAT 1
.SH NAME
stat \- print formatted inode contents
.SH SYNOPSIS
.B stat
file ...
.SH DESCRIPTION
For each file given as an argument
.I stat
formats the contents of the associated inode in a readable form,
and displays this information on the standard output.
.SH "SEE ALSO"
stat(2)

