.ig
	@(#)abs.3	1.1	7/6/83
	@(#)Copyright (C) 1983 by National Semiconductor Corp.
..
.TH ABS 3 
.SH NAME
abs \- integer absolute value
.SH SYNOPSIS
.nf
.B abs(i)
.B int i;
.fi
.SH DESCRIPTION
.I Abs
returns
the absolute value of its integer operand.
.SH SEE ALSO
floor(3) for
.I fabs
.SH BUGS
You get what the hardware gives on the smallest integer.
